import { Component } from '@angular/core';
import { PopoverController, NavController } from 'ionic-angular';

@Component({
  selector: 'page-food',
  templateUrl: 'food.html'
})

export class FoodPage {

  foods = [{name : 'aceite de oliva', definition : 'olive oil'},
  {name : 'aceite girasol', definition : 'sunflower oil'},
  {name : 'aguacate', definition : 'avocado'},
  {name : 'ahumados ', definition : 'smoked foods'},
  {name : 'ajo', definition : 'garlic'},
  {name : 'albaricoques', definition : 'apricots'},
  {name : 'albondigas', definition : 'meat balls'},
  {name : 'alcachofas', definition : 'artichokes'},
  {name : 'alcaparras', definition : 'capers'},
  {name : 'almejas', definition : 'clams'},
  {name : 'almendras', definition : 'almonds'},
  {name : 'alubias', definition : 'beans'},
  {name : 'anchoas', definition : 'anchovies'},
  {name : 'angulas', definition : 'baby eels'},
  {name : 'arroz', definition : 'rice'},
  {name : 'bacalao', definition : 'cod'},
  {name : 'barquillos', definition : 'biscuit rolls'},
  {name : 'batidos', definition : 'milk shakes'},
  {name : 'berenjenas', definition : 'aubergines / eggplant'},
  {name : 'berza', definition : 'cabbage'},
  {name : 'besugo', definition : 'sea bream'},
  {name : 'bistec de ternera', definition : 'veal steak'},
  {name : 'brazo de gitano', definition : 'Swiss roll'},
  {name : 'brevas', definition : 'figs'},
  {name : 'butifarra', definition : 'Catalan sausage'},
  {name : 'buñuelos', definition : 'light fried pastries'},
  {name : 'caballa', definition : 'Mackrel'},
  {name : 'con leche', definition : 'rice pudding'},
  {name : 'Cafe americano', definition : 'weak white coffee'},
  {name : 'café con leche', definition : 'white coffee'},
  {name : 'café cortado', definition : 'white coffee in small cup with very little milk'},
  {name : 'café sólo', definition : 'black coffee'},
  {name : 'calabacines', definition : 'courgettes/marrow'},
  {name : 'calamares', definition : 'squid rings'},
  {name : 'caldereta gallega', definition : 'vegetable stew'},
  {name : 'caldo', definition : 'soup'},
  {name : 'callos a la madrileña', definition : 'tripe Mdrid style'},
  {name : 'Camarones', definition : 'baby prawns'},
  {name : 'cangrejo', definition : 'crab'},
  {name : 'caracoles', definition : 'snails'},
  {name : 'caramelos', definition : 'sweets'},
  {name : 'carnes', definition : 'meats'},
  {name : 'castañas', definition : 'chestnuts'},
  {name : 'cebolla', definition : 'onion'},
  {name : 'cebolletas', definition : 'spring onions'},
  {name : 'centollo', definition : 'spider crab'},
  {name : 'cerezas', definition : 'cherries'},
  {name : 'cerveza', definition : 'beer'},
  {name : 'champiñónes', definition : 'mushrooms'},
  {name : 'chanquetes', definition : 'fish (similar to whitebait)'},
  {name : 'chirimoyas', definition : 'custard apples'},
  {name : 'chocos', definition : 'squid'},
  {name : 'chorizo', definition : 'cold spicy'},
  {name : 'chuleta de cerdo', definition : 'Pork chop'},
  {name : 'cordero', definition : 'lamb chops'},
  {name : 'churros', definition : 'fried pastry cut into lengths'},
  {name : 'cigalas', definition : 'crayfish'},
  {name : 'ciruelas', definition : 'plums'},
  {name : 'cochinillo asado', definition : 'roast suckling pig'},
  {name : 'cocido Madrileño', definition : 'stew with meat Spanish sausage chickpeas'},
  {name : 'codornice', definition : 'quail'},
  {name : 'coles de Bruselas', definition : 'Brussels sprouts'},
  {name : 'coliflor', definition : 'cauliflower'},
  {name : 'conejo', definition : 'rabbit'},
  {name : 'consomé al jerez', definition : 'consommé with sherry'},
  {name : 'crema catalana', definition : 'crème brulée'},
  {name : 'cremada', definition : 'sweet made with egg sugar and milk'},
  {name : 'dorada', definition : 'Gilt head fish'},
  {name : 'datiles', definition : 'dates'},
  {name : 'embutidos', definition : 'selection of cold sausages'},
  {name : 'empanada', definition : 'gallega tuna fish pastry'},
  {name : 'endivias', definition : 'endives (salad leaves)'},
  {name : 'ensaimada mallorquina', definition : 'Majorca cake'},
  {name : 'ensalada', definition : 'salad'},
  {name : 'ensaladilla rusa', definition : 'mayonnaise salad with potatoes carrots peas'},
  {name : 'entrecot', definition : 'entrêcot steak'},
  {name : 'entremeses de la casa', definition : 'homemade starters'},
  {name : 'escalope', definition : 'Breaded Meat'},
  {name : 'espinaca', definition : 'spinach'},
  {name : 'espárragos', definition : 'asparagus'},
  {name : 'estragón', definition : 'tarragon'},
  {name : 'fabada (asturiana)', definition : 'bean stew with Spanish sausage'},
  {name : 'faisán', definition : 'pheasant'},
  {name : 'fideos', definition : 'small noodles'},
  {name : 'filete', definition : 'filets of meat'},
  {name : 'flan', definition : 'cream caramel'},
  {name : 'fresas', definition : 'strawberries'},
  {name : 'fruta', definition : 'fruit'},
  {name : 'gallina', definition : 'chicken'},
  {name : 'gambas', definition : 'prawns'},
  {name : 'garbanzos', definition : 'chickpeas'},
  {name : 'guisantes', definition : 'peas'},
  {name : 'habas', definition : 'broad beans'},
  {name : 'habichuelas', definition : 'beans'},
  {name : 'helado', definition : 'ice cream'},
  {name : 'horchata', definition : 'cold almond-flavoured milk drink'},
  {name : 'huevo', definition : 'egg'},
  {name : 'Huevos fritos', definition : 'fried eggs'},
  {name : 'hígado', definition : 'liver'},
  {name : 'Jamón', definition : 'ham'},
  {name : 'Jabugo', definition : 'quality Spanish cured ham'},
  {name : 'jarra de vino', definition : 'jug of wine'},
  {name : 'jerez', definition : 'pale dry sherry'},
  {name : 'judías verdes', definition : 'French beans'},
  {name : 'jugo', definition : 'juice'},
  {name : 'langosta', definition : 'lobster'},
  {name : 'leche frita', definition : 'pudding with milk'},
  {name : 'Lechuga', definition : 'lettuce'},
  {name : 'lenguado', definition : 'sole'},
  {name : 'lentejas', definition : 'lentils'},
  {name : 'lombarda rellena', definition : 'stuffed red cabbage'},
  {name : 'lomo', definition : 'pork sausage'},
  {name : 'langostinos', definition : 'king prawns'},
  {name : 'lubina', definition : 'bass'},
  {name : 'Málaga Vino', definition : 'sweet wine'},
  {name : 'macarrones', definition : 'macarrones'},
  {name : 'mandarinas', definition : 'tangerines'},
  {name : 'manos de cerdo', definition : 'pigs’ trotters'},
  {name : 'mantecadas', definition : 'small sponge cakes'},
  {name : 'mantequilla', definition : 'butter manzanas'},
  {name : 'manzanilla', definition : 'dry sherry'},
  {name : 'mariscada', definition : 'cold mixed shellfish'},
  {name : 'mariscos', definition : 'shellfish'},
  {name : 'mejillones', definition : 'mussels'},
  {name : 'melocotones', definition : 'peaches'},
  {name : 'melón', definition : 'melon'},
  {name : 'merluza', definition : 'hake'},
  {name : 'mermelada', definition : 'marmalade'},
  {name : 'mero a la parrilla', definition : 'grouper'},
  {name : 'morcilla', definition : 'black pudding'},
  {name : 'mousse', definition : 'mousse'},
  {name : 'nabo', definition : 'turnip'},
  {name : 'naranjas', definition : 'oranges'},
  {name : 'natillas', definition : 'cold custard'},
  {name : 'nueces', definition : 'walnuts'},
  {name : 'nísperos', definition : 'Sharon fruit'},
  {name : 'orujo', definition : 'Grape Juice spirit'},
  {name : 'oreja (de cerdo)', definition : 'pigs’ ears'},
  {name : 'paella', definition : 'rice dish'},
  {name : 'paleta de cordero', definition : 'shoulder of lamb'},
  {name : 'pan', definition : 'bread'},
  {name : 'parrillada', definition : 'barbeque'},
  {name : 'pasteles', definition : 'cakes'},
  {name : 'patatas', definition : 'potatoes – Chips'},
  {name : 'pato', definition : 'Duck'},
  {name : 'pavo', definition : 'turkey'},
  {name : 'pollo', definition : 'chicken'},
  {name : 'pepinillos', definition : 'gherkins'},
  {name : 'pepino', definition : 'cucumber'},
  {name : 'peras', definition : 'peras'},
  {name : 'perdices', definition : 'partridges'},
  {name : 'perejil', definition : 'parsley'},
  {name : 'pescaditos fritos', definition : 'fried fish'},
  {name : 'pimientos', definition : 'red peppers'},
  {name : 'pinchos morunos', definition : 'kebabs'},
  {name : 'piña', definition : 'pineapple'},
  {name : 'piñones', definition : 'pine seeds'},
  {name : 'platanos', definition : 'bananas'},
  {name : 'pomelo', definition : 'grapefruit'},
  {name : 'potaje', definition : 'thick broth'},
  {name : 'puchero', definition : 'canario casserole'},
  {name : 'pulpitos', definition : 'baby octopus'},
  {name : 'potatoes puré', definition : 'mashed Potatoe'},
  {name : 'queso', definition : 'cheese'},
  {name : 'queso de oveja', definition : 'Sheep’s cheese'},
  {name : 'quisquillas', definition : 'shrimps'},
  {name : 'Ribeiro', definition : 'Galician white wine'},
  {name : 'ragout de ternera', definition : 'veal ragout'},
  {name : 'rape', definition : 'monk fish'},
  {name : 'raya', definition : 'skate'},
  {name : 'remolacha', definition : 'Beetroot'},
  {name : 'revuelto', definition : 'scrambled egg'},
  {name : 'riñones', definition : 'kidneys'},
  {name : 'rodaballo', definition : 'turbot'},
  {name : 'roscas', definition : 'sweet pastries'},
  {name : 'rábanos', definition : 'radish'},
  {name : 'salchichas', definition : 'sausages'},
  {name : 'salmonetes', definition : 'red mullet'},
  {name : 'salmón', definition : 'salmon'},
  {name : 'salmon ahumado', definition : 'smoked salmon'},
  {name : 'salsa', definition : 'sauce'},
  {name : 'sandía', definition : 'water melon'},
  {name : 'sardinas', definition : 'sardines'},
  {name : 'semidulce', definition : 'medium sweet'},
  {name : 'sesos', definition : 'brains'},
  {name : 'setas', definition : 'mushrooms'},
  {name : 'solomillo', definition : 'fillet steak'},
  {name : 'sopa', definition : 'soup'},
  {name : 'tallarines', definition : 'noodles'},
  {name : 'tarta de almendra', definition : 'almond tart'},
  {name : 'tarta', definition : 'tart'},
  {name : 'tomates', definition : 'tomatoes'},
  {name : 'tomillo', definition : 'thyme'},
  {name : 'torrijas', definition : 'sweet pastries'},
  {name : 'tortilla', definition : 'omelette'},
  {name : 'tournedó', definition : 'tournedos (fillet steak)'},
  {name : 'trucha', definition : 'trout'},
  {name : 'turrón', definition : 'nougat'},
  {name : 'uvas', definition : 'grapes'},
  {name : 'Valdepenas', definition : 'fruity red wines'},
  {name : 'vieiras', definition : 'scallops'},
  {name : 'vino blanco', definition : 'white wine'},
  {name : 'vino rosado', definition : 'rose wine'},
  {name : 'vino tinto', definition : 'red wine'},
  {name : 'zanahorias', definition : 'carrots'},
  {name : 'zarzuela de mariscos', definition : 'seafood stew'},
  {name : 'zumos', definition : 'juices'},
  {name : 'zumo de naranja', definition : 'orange juice'}];

  constructor(public navCtrl: NavController, public popoverCtrl: PopoverController) {

  }

}
